### ISSUE TITLE
Assign handle to new users

### ISSUE THREAD

**Issue by Benjamindodgson** [Benji-Inc/benji-backend#17]
Create and assign handle to new users that do not already have a handle, and have the following: 

A reservation that has been claimed.
A valid first and last name.
A valid phone number.

**Comment by benpetty** [comment]
https://github.com/Benji-Inc/benji-backend/commit/7b298a74ffc0dd3e4445e0d9e66cd09e623aa0e8

**Comment by benpetty** [comment]
https://github.com/Benji-Inc/benji-backend/commit/7b298a74ffc0dd3e4445e0d9e66cd09e623aa0e8

**Comment by benpetty** [comment]
Cloud function and webhook have been implemented and deployed
