### ISSUE TITLE
Add people to channel when channel is created

### ISSUE THREAD

**Issue by Benjamindodgson** [Benji-Inc/benji-backend#76]
When playing around with this, I realized it was overkill to have wait for people to join a channel. By having everyone added right away it also solves a problem of a user sending an alert message before the other user has joined.

**Comment by santiagosemhan** [comment]
Use Twilio chat after webhook 'onChannelAdded'. Example payload: 

`{
  "CreatedBy": "r1RXXXXHg",
  "FriendlyName": "development",
  "EventType": "onChannelAdded",
  "InstanceSid": "IS2bbXXXXXX480eb948f985d10ca201",
  "Attributes": "{\"context\":\"important\"}",
  "DateCreated": "2020-05-15T00:19:43.947Z",
  "AccountSid": "XXXXXXX",
  "Source": "SDK",
  "ChannelSid": "CH6c6955XXXXX79b3d518bda1ff267",
  "ClientIdentity": "rXXXXXm6zHg",
  "RetryCount": "0",
  "ChannelType": "private",
  "UniqueName": "885754B9-XXXX-49E7-XXXX-EF6F3B31EAD0"
}`
