### ISSUE TITLE
Send notification when a user joins Benji to a the user that invited them

### ISSUE THREAD

**Issue by Benjamindodgson** [Benji-Inc/benji-backend#97]
When a connection has been made between two users, send a notification to the from user with channelId from the connection attached. 

title = "(Name) joined! 🎉"
message = "(Name) accepted your invitation and is now available to chat with!"

**Comment by santiagosemhan** [comment]
@Benjamindodgson can you describe the notification payload format? 

For instance:
```js
const data = {
     messageId: MessageSid,
     channelId: ChannelSid,
     identifier: MessageSid + context,
     title: 'Emergency 🚨',
     body: Body,
     target: 'channel',
};
```

**Comment by santiagosemhan** [comment]
Send twilio message instead of push notification.
